"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import {
  LayoutDashboard,
  Camera,
  FileText,
  Clock,
  BarChart3,
  Settings,
  Utensils,
  Home,
  Smile,
  Download,
  ExternalLink,
  Calendar,
  Star,
  Filter,
  Search,
  ChevronLeft,
} from "lucide-react";

const sidebarItems = [
  { icon: <LayoutDashboard className="w-4 h-4" />, label: "Overview", href: "/dashboard" },
  { icon: <Camera className="w-4 h-4" />, label: "Camera", href: "/camera" },
  { icon: <FileText className="w-4 h-4" />, label: "Reports", href: "/reports", active: true },
  { icon: <Clock className="w-4 h-4" />, label: "History", href: "/history" },
  { icon: <BarChart3 className="w-4 h-4" />, label: "Analytics", href: "/analytics" },
  { icon: <Settings className="w-4 h-4" />, label: "Settings", href: "/settings" },
];

type ReportType = "food" | "room" | "emotion";

interface Report {
  id: string;
  type: ReportType;
  title: string;
  summary: string;
  score: number;
  date: string;
  pages: number;
  highlights: string[];
  color: string;
}

const REPORTS: Report[] = [
  {
    id: "r1",
    type: "food",
    title: "Weekly Nutrition Report",
    summary: "Comprehensive analysis of your eating habits over the past 7 days. Trends show improved protein intake.",
    score: 8.2,
    date: "Jun 11, 2026",
    pages: 6,
    highlights: ["Daily avg: 2,100 kcal", "Protein goal: 94% achieved", "Hydration: needs attention"],
    color: "#10B981", // Emerald Green
  },
  {
    id: "r2",
    type: "room",
    title: "Home Design Assessment",
    summary: "Full interior design evaluation across 4 rooms. Living room scored highest; bedroom needs lighting improvements.",
    score: 7.5,
    date: "Jun 10, 2026",
    pages: 9,
    highlights: ["Living Room: 8.3/10", "Bedroom: 6.8/10", "Kitchen: 7.9/10"],
    color: "#0070F3", // Primary Blue
  },
  {
    id: "r3",
    type: "emotion",
    title: "Emotion Trend Analysis",
    summary: "30-day emotional state tracking. Confidence levels increased significantly week-over-week.",
    score: 8.7,
    date: "Jun 9, 2026",
    pages: 7,
    highlights: ["Avg happiness: 74%", "Confidence trend: +12%", "Stress markers: Low"],
    color: "#0EA5E9", // Sky Blue
  },
  {
    id: "r4",
    type: "food",
    title: "Macronutrient Breakdown",
    summary: "Detailed macro and micronutrient breakdown for the month of May with dietary recommendations.",
    score: 7.9,
    date: "Jun 1, 2026",
    pages: 5,
    highlights: ["Carb ratio optimal", "Iron: slightly deficient", "Vitamin D: supplementation advised"],
    color: "#10B981",
  },
  {
    id: "r5",
    type: "room",
    title: "Office Ergonomics Report",
    summary: "AI analysis of your workspace setup for ergonomics, lighting, and productivity optimization.",
    score: 8.4,
    date: "May 28, 2026",
    pages: 4,
    highlights: ["Monitor height: optimal", "Lighting score: 8.1/10", "Chair posture: adjust lower back"],
    color: "#0070F3",
  },
  {
    id: "r6",
    type: "emotion",
    title: "Interview Readiness Report",
    summary: "Pre-interview confidence and emotional readiness analysis. Eye contact and expression coaching included.",
    score: 9.1,
    date: "May 25, 2026",
    pages: 5,
    highlights: ["Eye contact: Excellent", "Smile frequency: High", "Posture: Professional"],
    color: "#0EA5E9",
  },
];

const typeIcons: Record<ReportType, React.ReactNode> = {
  food: <Utensils className="w-5 h-5" />,
  room: <Home className="w-5 h-5" />,
  emotion: <Smile className="w-5 h-5" />,
};

const typeLabels: Record<ReportType, string> = {
  food: "Food Intelligence",
  room: "Interior AI",
  emotion: "Human Analysis",
};

export default function ReportsPage() {
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<"all" | ReportType>("all");

  const filtered = REPORTS.filter((r) => {
    if (filter !== "all" && r.type !== filter) return false;
    if (search && !r.title.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  const handleDownload = (report: Report) => {
    const content = `ANTOS INTELLIGENCE REPORT\n${"=".repeat(40)}\n\nTitle: ${report.title}\nDate: ${report.date}\nType: ${typeLabels[report.type]}\nAI Score: ${report.score}/10\n\nSummary:\n${report.summary}\n\nKey Highlights:\n${report.highlights.map((h) => `• ${h}`).join("\n")}\n\n${"=".repeat(40)}\nGenerated by Antos Intelligence AI Vision Platform`;
    const blob = new Blob([content], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `antos-${report.type}-report-${Date.now()}.txt`;
    a.click();
  };

  return (
    <div className="flex min-h-screen bg-[#F8FAFC] text-[#0F172A]">
      {/* Sidebar */}
      <aside className="hidden lg:flex flex-col w-60 border-r border-slate-200 bg-white p-4 gap-1">
        <Link href="/" className="flex items-center gap-2.5 px-3 py-4 mb-4 group">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#0070F3] to-[#0051B3] flex items-center justify-center shadow-sm">
            <LayoutDashboard className="w-4 h-4 text-white" />
          </div>
          <div className="flex flex-col leading-none">
            <span className="font-display font-bold text-slate-900 text-sm">
              Antos <span className="text-[#0070F3]">Intelligence</span>
            </span>
            <span className="text-[8px] text-slate-400 font-mono tracking-wider mt-0.5">CONSOLE</span>
          </div>
        </Link>

        {sidebarItems.map((item) => (
          <Link
            key={item.label}
            href={item.href}
            className={`flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all ${
              item.active
                ? "bg-[#0070F3]/10 text-[#0070F3] border border-[#0070F3]/20"
                : "text-slate-600 hover:text-slate-900 hover:bg-slate-100"
            }`}
          >
            {item.icon}
            {item.label}
          </Link>
        ))}

        <div className="mt-auto flex flex-col gap-2">
          <Link
            href="/"
            className="flex items-center justify-center gap-2 w-full px-3 py-2.5 rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50 text-sm font-semibold transition-colors"
          >
            <ChevronLeft className="w-4 h-4" /> Back to Portal
          </Link>
          <Link href="/camera" className="flex items-center justify-center gap-2 w-full px-3 py-2.5 rounded-lg bg-[#0070F3] hover:bg-[#0051B3] text-white text-sm font-semibold shadow-sm transition-colors">
            <Camera className="w-4 h-4" /> New Analysis
          </Link>
        </div>
      </aside>

      {/* Main */}
      <main className="flex-1 p-6 lg:p-8 overflow-y-auto max-w-7xl mx-auto w-full">
        {/* Mobile top bar */}
        <div className="flex items-center justify-between mb-6 lg:hidden">
          <Link href="/" className="inline-flex items-center gap-1.5 text-xs text-[#0070F3] font-semibold">
            <ChevronLeft className="w-4 h-4" /> Portal
          </Link>
          <div className="text-right">
            <span className="text-xs font-bold text-slate-800">Antos Intelligence</span>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
          <div>
            <h1 className="text-2xl font-black text-slate-900 font-display">Reports</h1>
            <p className="text-sm text-slate-500 mt-1">AI-generated analysis reports from your scans.</p>
          </div>
          <Link
            href="/camera"
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#0070F3] hover:bg-[#0051B3] text-white text-sm font-semibold shadow-sm transition-all self-start sm:self-auto"
          >
            <Camera className="w-4 h-4" /> Generate Report
          </Link>
        </div>

        {/* Search + filter */}
        <div className="flex flex-col sm:flex-row gap-3 mb-6">
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input
              type="text"
              placeholder="Search reports..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full bg-white border border-slate-200 rounded-lg pl-9 pr-4 py-2.5 text-sm text-slate-800 placeholder:text-slate-400 focus:outline-none focus:border-[#0070F3]/50 focus:ring-1 focus:ring-[#0070F3]/30"
            />
          </div>
          <div className="flex items-center gap-2 overflow-x-auto pb-1.5 sm:pb-0 scrollbar-none">
            {(["all", "food", "room", "emotion"] as const).map((f) => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all capitalize border ${
                  filter === f
                    ? "bg-[#0070F3]/10 text-[#0070F3] border-[#0070F3]/25 font-bold"
                    : "bg-white text-slate-600 border-slate-200 hover:bg-slate-50"
                }`}
              >
                {f}
              </button>
            ))}
          </div>
        </div>

        {/* Reports grid */}
        <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">
          {filtered.map((report, i) => (
            <motion.div
              key={report.id}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              className="bg-white border border-slate-200 rounded-xl overflow-hidden hover-card flex flex-col shadow-sm"
            >
              {/* Header */}
              <div className="p-5 border-b border-slate-100">
                <div className="flex items-start gap-3">
                  <div
                    className="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0"
                    style={{ background: `${report.color}10`, color: report.color }}
                  >
                    {typeIcons[report.type]}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div
                      className="text-xs font-bold mb-0.5"
                      style={{ color: report.color }}
                    >
                      {typeLabels[report.type]}
                    </div>
                    <h3 className="text-sm font-semibold text-slate-900 leading-snug">{report.title}</h3>
                  </div>
                  <div
                    className="text-lg font-black flex-shrink-0"
                    style={{ color: report.color }}
                  >
                    {report.score}
                  </div>
                </div>
              </div>

              {/* Body */}
              <div className="p-5 flex-1 flex flex-col justify-between">
                <p className="text-xs text-slate-500 leading-relaxed mb-4">{report.summary}</p>

                <div className="space-y-1.5 mb-4">
                  {report.highlights.map((h, j) => (
                    <div key={j} className="flex items-center gap-2">
                      <Star className="w-3.5 h-3.5 flex-shrink-0" style={{ color: report.color }} />
                      <span className="text-xs text-slate-600">{h}</span>
                    </div>
                  ))}
                </div>

                <div className="flex items-center gap-2 text-xs text-slate-400 font-mono">
                  <Calendar className="w-3.5 h-3.5" />
                  {report.date}
                  <span className="ml-auto">{report.pages} pages</span>
                </div>
              </div>

              {/* Actions */}
              <div className="p-4 border-t border-slate-100 flex gap-2">
                <button
                  onClick={() => handleDownload(report)}
                  className="flex-1 flex items-center justify-center gap-2 py-2 rounded-lg bg-slate-50 border border-slate-200 text-slate-600 text-xs font-semibold hover:bg-slate-100 transition-all"
                >
                  <Download className="w-3.5 h-3.5" /> Download
                </button>
                <button className="flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-xs font-semibold transition-all border"
                  style={{ background: `${report.color}10`, color: report.color, borderColor: `${report.color}25` }}
                >
                  <ExternalLink className="w-3.5 h-3.5" /> View Full
                </button>
              </div>
            </motion.div>
          ))}
        </div>

        {filtered.length === 0 && (
          <div className="flex flex-col items-center justify-center py-20 gap-4">
            <FileText className="w-12 h-12 text-slate-200" />
            <p className="text-slate-400 text-sm">No reports found</p>
          </div>
        )}
      </main>
    </div>
  );
}
